### ISSUE TITLE
Sleep function

### ISSUE THREAD

**Issue by DonFabo** [bodzio528/FS22_CropRotation#26]
Hello, with the new version 2.5.0.0 I can go to sleep at the farmhouse, but the sleep function does not end and continues indefinitely.
The sleep function does not end even if only Croprotation is activated.

**Comment by Hilbert1982** [comment]
below is a part of the log file. if i go back to the previous version it's oke.
if you needed i can upload the whole logfile, let me know.
2023-08-08 22:18 Game saved successfully.
2023-08-08 22:19  DensityMapUpdater: INFO schedule UpdateRegrow
2023-08-08 22:19  DensityMapUpdater: INFO start processing UpdateRegrow
2023-08-08 22:19 Error: Running LUA method 'update'.
C:/Users/hriel/OneDrive/Documenten/My Games/FarmingSimulator2022/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-08 22:19 Error: Running LUA method 'update'.
C:/Users/hriel/OneDrive/Documenten/My Games/FarmingSimulator2022/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)

**Comment by jfoppe** [comment]
I could "fix" it by adding the line `self.fruitTypeManager = g_fruitTypeManager` at the begin of the function `CropRotation:task_updateRegrow` (Line 1500 in CropRotation.lua). But i don't know if this realy fix the issue or if it breaks other functions.

> function CropRotation:task_updateRegrow(startWorldX, startWorldZ, widthWorldX, widthWorldZ, heightWorldX, heightWorldZ)
>
>    local terrainSize = g_currentMission.terrainSize or 1024
>    local modifiers = self.modifiers
>    self.fruitTypeManager = g_fruitTypeManager
>
>    for i, desc in pairs(self.fruitTypeManager:getFruitTypes()) do
>   ...

**Comment by Bogy121** [comment]
Yup, same thing here. Sleep function no longer works properly

**Comment by Bogy121** [comment]
I just noticed that new hotfix was released which fixes this issue. You may close this :)
