### ISSUE TITLE
New version doesn't work on LaCoronella

### ISSUE THREAD

**Issue by etrigo1** [bodzio528/FS22_CropRotation#28]
Hello, I used this mod on the LaCoronella map and since the update the mod stopped working. Crashes the loading screen at 95%.

![image](https://github.com/bodzio528/FS22_CropRotation/assets/37108041/3d616ecd-7cbf-43fc-a0dd-12cd50368563)
[log.txt](https://github.com/bodzio528/FS22_CropRotation/files/12324987/log.txt)

**Comment by MacPlatters** [comment]
The issue isn't related to the map, it appears. I have the same error and problem on my game in Haut-Beyleron. Updating to 2.5.0.1 didn't resolve it. Strangely, for me at least, disabling "LFHA ForageOptima Standard" did resolve it.

**Comment by etrigo1** [comment]
Hello, yes, I disabled the LFHA and it already worked.

**Comment by etrigo1** [comment]
Hello, yes, I disabled the LFHA and it already worked.
