### ISSUE TITLE
wersja 2.5.0.0

### ISSUE THREAD

**Issue by 00-Mario-00** [bodzio528/FS22_CropRotation#30]
w poprzedniej wersji było ok, po aktualizacji do 2.5 serwer dedykowany wywala błedy i wyswietla komunikat czekam na akceptacje hosta i nie da sie wejsc...
po przyrócenuu do wczesniejszej wersji wszystko jest ok

C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTypeManager' (a nil value)
2023-08-13 09:11 Error: Running LUA method 'update'.
C://SERVICES//ni2354758_2_local//lws22//profile/mods/FS22_CropRotation/CropRotation.lua:1504: attempt to index field 'fruitTy

**Comment by queenofdamed** [comment]
i have the same ishue i sleep and the game stuck sleeping log shows this spammed

**Comment by bojanh66** [comment]
I have the same issue.

**Comment by acesyde** [comment]
I same issue here

**Comment by bodzio528** [comment]
fixed in 2.5.0.1-hotfix
