### ISSUE TITLE
All fields disappeared on first planting season

### ISSUE THREAD

**Issue by shockrift** [bodzio528/FS22_CropRotation#32]
On Green Valley Nebraska when I reached close to midnight of the first planting month there were a ton of planting/harvesting contracts as you'd expect and then all the fields disappeared. Apologies I don't the logs as the document wasn't saved but I recall the logs complaining that it could not identify filltype nil.

Once crop rotation was removed, save reloaded, and went past midnight the fields were fine. To clarify, when I say that all fields disappeared they did so in the PDA, map, field calculator, etc. so the zones stopped being defined. 

Steps to reproduce I guess would be to load GV Nebraska with the anhydrous precision farming mod fast forward and see if behavior observed.

**Comment by bodzio528** [comment]
fixed in 2.5.0.1-hotfix
