### ISSUE TITLE
Fix the Penalty for crop destruction

### ISSUE THREAD

**Issue by Oskicz** [bodzio528/FS22_CropRotation#38]
I'm getting penalty for driving on contract field or just grass awesome mod i'm waiting for FIX!
(I can't find github of this one your's mod so i put it here)

**Comment by bodzio528** [comment]
Hi, there it is https://github.com/bodzio528/FS22_NoTrespassing

please include which map is this issue visible? Custom maps sometimes redefine value for "No Owner" which may be the case.
