### ISSUE TITLE
2.5.0.2 release zip is defective

### ISSUE THREAD

**Issue by Gordon-Dry** [bodzio528/FS22_CropRotation#44]
It got some duplicate files within the same folder, which is not normal and only can happen in a defective archive.

**Comment by Bogy121** [comment]
Confirming this. If you try to extract the archive, duplicates will appear.

**Comment by bodzio528** [comment]
Sure, archive was corrupted by faulty buildscript.

duplications removed, file uploaded again under the same link.

https://github.com/bodzio528/FS22_CropRotation/releases/tag/v2.5.0.2
